elit_module:
    resource: "@ElitBundle/Resources/config/routing/module.yml"
    prefix:   /module

elit_lessons:
    resource: "@ElitBundle/Resources/config/routing/lessons.yml"
    prefix:   /lessons

elit_rendez:
    resource: "@ElitBundle/Resources/config/routing/rendezvous.yml"
    prefix:   /rendez

elit_application:
    resource: "@ElitBundle/Resources/config/routing/application.yml"
    prefix:   /application


elit_classes:
    resource: "@ElitBundle/Resources/config/routing/classes.yml"
    prefix:   /classes

elit_homepage:
    path:     /
    defaults: { _controller: ElitBundle:Default:index }

ajout_student:
    path:     /S
    defaults: { _controller: ElitBundle:Student:ajout }


affiche_student:
    path:     /A
    defaults: { _controller: ElitBundle:Student:affiche }

elit_classrooms:
        resource: "@ElitBundle/Resources/config/routing/classrooms.yml"
        prefix:   /classrooms
elit_equipement:
    resource: "@ElitBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement

